<a href="https://colab.research.google.com/github/VaishaliMJ/Machine_Learning/blob/main/KNN_Imputation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("train.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
titanic=df[['Age','Pclass','Fare','Survived']]

titanic.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [6]:
titanic.isnull().sum()

Age         177
Pclass        0
Fare          0
Survived      0
dtype: int64

In [7]:
titanic.isnull().mean()*100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.impute import SimpleImputer,KNNImputer

In [9]:
x=titanic.drop(columns=['Survived'],axis=1)
y=titanic['Survived']

In [10]:
xTrain,xTest,yTrain,yTest=train_test_split(x,y,test_size=0.2,random_state=2)

In [24]:
knnImputor=KNNImputer(n_neighbors=3,weights='uniform')
xTrain_trf=knnImputor.fit_transform(xTrain)
xTest_trf=knnImputor.transform(xTest)

In [25]:
pd.DataFrame(xTrain_trf,columns=xTrain.columns)

           Age  Pclass      Fare
0    40.000000     1.0   27.7208
1     4.000000     3.0   16.7000
2    47.000000     3.0    9.0000
3     9.000000     3.0   31.3875
4    20.000000     3.0    9.8458
..         ...     ...       ...
707  30.000000     3.0    8.6625
708  26.000000     3.0    8.7125
709  71.000000     1.0   49.5042
710  32.666667     1.0  221.7792
711  53.333333     1.0   25.9250

[712 rows x 3 columns]

In [26]:
lr=LogisticRegression()
lr.fit(xTrain_trf,yTrain)
yPred=lr.predict(xTest_trf)
accuracy_score(yTest,yPred)

0.7039106145251397

In [29]:
simpleImputor=SimpleImputer()
xTrain_trf2=simpleImputor.fit_transform(xTrain)
xTest_trf2=simpleImputor.transform(xTest)

lr=LogisticRegression()
lr.fit(xTrain_trf2,yTrain)
yPred=lr.predict(xTest_trf2)
accuracy_score(yTest,yPred)

0.6927374301675978